version: "3.5"

volumes:
  postgres_data:
      driver: local

services:
  keycloak_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: changeme-postgres
    networks:
      transit_idp:
    labels:
      - "traefik.enable=false"

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    hostname: keycloak
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=keycloak_db
      - DB_DATABASE=keycloak
      - DB_PORT=5432
      - DB_USER=keycloak
      - DB_SCHEMA=public
      - DB_PASSWORD=changeme-postgres
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_LOGLEVEL=INFO
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=changeme-keycloak
    networks:
      transit_idp:
    labels:
      - traefik.port=8443
      - traefik.frontend.rule=Host:auth.idocker.hacking-lab.com
      - traefik.protocol=https
    command: ["-b", "0.0.0.0", "-Dkeycloak.profile.feature.docker=enabled"]


networks:
  transit_idp:
    external: true
